# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tnbassist < Formula
  desc ""
  homepage "https://github.com/open-blockchain-explorer/tnbassist"
  version "0.0.2-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/open-blockchain-explorer/tnbassist/releases/download/v0.0.2-alpha/tnbassist_0.0.2-alpha_Darwin_x86_64.tar.gz"
      sha256 "8da456577f7f43a47b9377b8a776b2b30f65b8443d339d2ec781175be9e206c6"

      def install
        bin.install "tnbassist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/open-blockchain-explorer/tnbassist/releases/download/v0.0.2-alpha/tnbassist_0.0.2-alpha_Darwin_arm64.tar.gz"
      sha256 "f118325e76db0485403874c06a7fdba9ec83a7904081ebb0b286b9ffaab6f042"

      def install
        bin.install "tnbassist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/open-blockchain-explorer/tnbassist/releases/download/v0.0.2-alpha/tnbassist_0.0.2-alpha_Linux_arm64.tar.gz"
      sha256 "102c6556f37908df65a6ebc3f9117c416d7f3a5fe7a56c97b213f1141182317b"

      def install
        bin.install "tnbassist"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/open-blockchain-explorer/tnbassist/releases/download/v0.0.2-alpha/tnbassist_0.0.2-alpha_Linux_x86_64.tar.gz"
      sha256 "5fa391dc89fcfe535a9f3a500fc7500f0cfa4d1356b78179ae042e901e962722"

      def install
        bin.install "tnbassist"
      end
    end
  end
end
